### ISSUE TITLE
Download wget from cart only works once (https://aims2.llnl.gov/search)

### ISSUE THREAD

**Issue by mo-garethsjones** [esgf2-us/metagrid#654] opened 2024-08-20 13:59 UTC
### Describe the bug

Trying to retrieve data from https://aims2.llnl.gov/search via the cart and download of wget.
Works first time, but not on subsequent attempts. 
In "Download your cart" section of cart, choosing wget but then clicking on "Download" does nothing.
Only if I clear the cookie cache on the browser will it work. 
But that means all the search selections already made are cleared.
So if downloading multiple wgets for slightly different selections means repeating the clearing of cookies and entering the same selections each time.

Tried it on different devices (mac, linux, windows) with browsers
Firefox : 115.12.Oesr, 115.14.Oesr, 129.0.1, 
Chrome: Version 127.0.6533.120
Edge: Version 127.0.2651.10

#### To Reproduce

From https://aims2.llnl.gov/search 

First attempt
Selected 
Source ID: HadGEM3-GC31-LL
experiment ID: hist-volc
Variable ID: tas
Frequency: mon
Variant label: r18i1p1f3
Select dataset CMIP6.DAMIP.MOHC.HadGEM3-GC31-LL.hist-volc.r18i1p1f3.Amon.tas.gn
Click on 'add selected to cart'
In cart, select dataset, in Download your cart" section of cart, choose wget and click on "Download". wget file is downloaded.
Click on clear cart.

Second attempt
Back in search change one of the search entries
Variant label: r11i1p1f3
and repeat the above steps. This time, clicking on download does nothing.

#### Expected behavior

The download option will work each time without clearing cookie cache.

**Comment by sashakames** [comment] 2024-09-05 23:55
I can confirm this issue.  Test if also a problem on the more recent version on https://esgf-dev1.llnl.gov/

**Comment by downiec** [comment] 2024-09-06 01:58
Strange, I tried repeating this issue on my end. Tried Chrome and Firefox, logged in and not logged in, and I used the exact same dataset as described in the issue. I wasn't able to replicate the issue, I tried this on aims2 by the way. I'll have to dig deeper to understand what could be the cause

**Comment by sashakames** [comment] 2024-09-06 03:11
Problem persists on esgf-dev1 so recent fixes didn't cover this issue.  How about splitting the button into separate ones for wget and Globus so the button become less complicated?

**Comment by sashakames** [comment] 2024-09-10 23:39
We have pushed a fix of this issue to our development-test server:  https://esgf-dev1.llnl.gov/cart/items
The update to production will be completed soon.

**Comment by sashakames** [comment] 2024-09-24 20:34
The bugfix has been pushed to the aims2 server now as well.

**Closed by sashakames** 2024-09-24 20:34 UTC
